services:
  mongodb:
    image: mongo:8
    container_name: hr-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: hr-management

volumes:
  mongodb_data:
