services:
  postgres:
    image: postgres:16
    container_name: hr--management-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hr_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
