import { createContext, useContext, useState, ReactNode, useCallback } from 'react';

export type Lang = 'en' | 'vi';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'app.name': 'HR Management',
    'role.admin': 'Admin',
    'role.manager': 'Manager',
    'role.employee': 'Employee',
    'nav.dashboard': 'Dashboard',
    'nav.employees': 'Employees',
    'nav.departments': 'Departments',
    'nav.org_chart': 'Org Chart',
    'nav.leaves': 'Leaves',
    'nav.leave_approvals': 'Leave Approvals',
    'nav.attendance': 'Attendance',
    'nav.attendance_report': 'Attendance Report',
    'nav.payroll': 'Payroll',
    'nav.payroll_management': 'Payroll Management',
    'nav.performance_reviews': 'Performance Reviews',
    'nav.performance_management': 'Review Management',
    'nav.job_postings': 'Job Postings',
    'nav.candidates': 'Candidates',
    'nav.notifications': 'Notifications',
    'nav.logout': 'Logout',
    'performance_reviews.my_title': 'My Performance Reviews',
    'performance_reviews.description': 'View your performance evaluations',
    'performance_reviews.no_reviews': 'No performance reviews found',
    'settings': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'user.edit_profile': 'Edit Profile',
    'user.profile': 'Profile',
    'user.name': 'Name',
    'user.email': 'Email',
    'user.role': 'Role',
    'user.save': 'Save',
    'user.info': 'User Information',
    'dialog.cancel': 'Cancel',
    'profile.updated': 'Profile updated',
    'profile.failed_update': 'Failed to update profile',
    'profile.security': 'Security',
    'profile.change_password': 'Change Password',
    'profile.edit_sr': 'Edit user profile',
    'profile.password_sr': 'Update your password',
    'profile.current_password': 'Current Password',
    'profile.new_password': 'New Password',
    'profile.confirm_password': 'Confirm New Password',
    'profile.passwords_mismatch': 'Passwords do not match',
    'profile.password_changed': 'Password changed successfully',
    'profile.password_failed': 'Failed to change password',
    'dashboard.title': 'Dashboard',
    'dashboard.total_employees': 'Total Employees',
    'dashboard.pending_leaves': 'Pending Leaves',
    'dashboard.present_today': 'Present Today',
    'dashboard.monthly_payroll': 'Monthly Payroll',
    'dashboard.recent_leaves': 'Recent Leaves',
    'dashboard.quick_stats': 'Quick Stats',
    'dashboard.no_leaves': 'No leaves found',
    'dashboard.my_leaves': 'My Leaves',
    'dashboard.my_attendance': 'My Attendance',
    'dashboard.welcome_back': 'Welcome back',
    'dashboard.approved': 'Approved',
    'dashboard.rejected': 'Rejected',
    'dashboard.present_month': 'Present (This Month)',
    'dashboard.month_days': 'This Month Days',
    'dashboard.attendance_records': 'attendance records',
    'dashboard.leave_breakdown': 'Leave Breakdown',
    'dashboard.no_leave_data': 'No leave data',
    'dashboard.attendance_month': 'Attendance (This Month)',
    'dashboard.no_attendance_data': 'No attendance data',
    'dashboard.upcoming_leaves': 'Upcoming Leaves',
    'dashboard.present': 'Present',
    'dashboard.late': 'Late',
    'dashboard.half_day': 'Half Day',
    'dashboard.absent': 'Absent',
    'dashboard.team_overview': 'Team overview',
    'dashboard.company_overview': 'Company overview',
    'dashboard.employees_per_dept': 'Employees per Department',
    'dashboard.no_department_data': 'No department data',
    'dashboard.department_title': 'Department',
    'dashboard.team_size': 'Team Size',
    'dashboard.dept_payroll': 'Dept Payroll',
    'dashboard.na': 'N/A',
    'dashboard.pending': 'pending',
    'dashboard.days': 'days',
    'dashboard.employees': 'Employees',
    'dashboard.departments': 'Departments',
    'employees.title': 'Employees',
    'employees.add': 'Add Employee',
    'employees.search': 'Search employees...',
    'employees.name': 'Name',
    'employees.position': 'Position',
    'employees.department': 'Department',
    'employees.salary': 'Salary',
    'employees.no_results': 'No employees found',
    'employees.first_name': 'First Name',
    'employees.last_name': 'Last Name',
    'employees.hire_date': 'Hire Date',
    'employees.phone': 'Phone',
    'employees.user_id': 'User ID',
    'employees.user_id_placeholder': 'User ID from registration',
    'employees.create': 'Create',
    'departments.title': 'Departments',
    'departments.add': 'Add Department',
    'departments.search': 'Search departments...',
    'departments.name': 'Name',
    'departments.description': 'Description',
    'departments.manager': 'Manager',
    'departments.actions': 'Actions',
    'departments.no_results': 'No departments',
    'departments.create': 'Create',
    'departments.edit': 'Edit Department',
    'departments.save': 'Save',
    'departments.delete': 'Delete Department',
    'departments.delete_confirm': 'Are you sure you want to delete',
    'departments.delete_warning': 'This action cannot be undone.',
    'departments.created': 'Department created',
    'departments.updated': 'Department updated',
    'departments.deleted': 'Department deleted',
    'leaves.title': 'My Leaves',
    'leaves.request': 'Request Leave',
    'leaves.type': 'Type',
    'leaves.start': 'Start',
    'leaves.end': 'End',
    'leaves.status': 'Status',
    'leaves.reason': 'Reason',
    'leaves.no_results': 'No leaves',
    'leaves.request_title': 'Request Leave',
    'leaves.annual': 'Annual',
    'leaves.sick': 'Sick',
    'leaves.personal': 'Personal',
    'leaves.start_date': 'Start Date',
    'leaves.end_date': 'End Date',
    'leaves.submit': 'Submit',
    'leaves.approvals': 'Leave Approvals',
    'leaves.employee': 'Employee',
    'leaves.actions': 'Actions',
    'leaves.no_pending': 'No pending leaves',
    'attendance.title': 'My Attendance',
    'attendance.check_in': 'Check In',
    'attendance.check_out': 'Check Out',
    'attendance.date': 'Date',
    'attendance.status': 'Status',
    'attendance.no_records': 'No records',
    'attendance.already_checked_in': 'Already checked in today',
    'attendance.check_out_failed': 'Check out failed',
    'attendance.report': 'Attendance Report',
    'attendance.employee': 'Employee',
    'payroll.title': 'My Payroll',
    'payroll.period': 'Period',
    'payroll.basic_salary': 'Basic Salary',
    'payroll.bonus': 'Bonus',
    'payroll.deductions': 'Deductions',
    'payroll.net_pay': 'Net Pay',
    'payroll.status': 'Status',
    'payroll.no_records': 'No payroll records',
    'payroll.management': 'Payroll Management',
    'payroll.process': 'Process Payroll',
    'payroll.employee': 'Employee',
    'payroll.actions': 'Actions',
    'payroll.mark_paid': 'Mark Paid',
    'payroll.month': 'Month',
    'payroll.year': 'Year',
    'payroll.employees': 'Employees',
    'payroll.process_btn': 'Process',
    'payroll.no_records_management': 'No payroll records',
    'payroll.total_paid': 'Total Paid',
    'payroll.waiting': 'Waiting',
    'payroll.paid': 'Paid',
    'payroll.draft': 'Draft',
    'payroll.gross': 'Gross Pay',
    'payroll.process_description': 'Process payroll for selected employees',
    'employees.contract': 'Contract',
    'employees.contract_type': 'Contract Type',
    'employees.contract_expiry': 'Contract Expiry',
    'employees.contract_permanent': 'Permanent',
    'employees.contract_contract': 'Contract',
    'employees.contract_intern': 'Intern',
    'employees.documents': 'Documents',
    'employees.history': 'Employee History',
    'employees.history_add': 'Add Entry',
    'employees.history_title': 'Add History Entry',
    'employees.history_type': 'Type',
    'employees.history_previous': 'Previous Value',
    'employees.history_new': 'New Value',
    'employees.history_date': 'Effective Date',
    'employees.history_note': 'Note',
    'employees.history_save': 'Save',
    'employees.history_added': 'History entry added',
    'employees.not_found': 'Employee not found',
    'employees.no_history': 'No history entries',
    'employees.history_previous_placeholder': 'e.g. $3,000 / Junior',
    'employees.history_new_placeholder': 'e.g. $4,000 / Senior',
    'employees.history_note_placeholder': 'Optional note',
    'history.raise': 'Raise',
    'history.promotion': 'Promotion',
    'history.transfer': 'Transfer',
    'history.other': 'Other',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'notifications.unread': 'unread',
    'notifications.all_caught_up': 'All caught up',
    'notifications.mark_all_read': 'Mark all read',
    'notifications.no_notifications': 'No notifications',
    'notifications.up_to_date': "You're all up to date",
    'notifications.failed_mark_read': 'Failed to mark as read',
    'login.sign_in_to_account': 'Sign in to your account',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.sign_in': 'Sign In',
    'login.demo_accounts': 'Demo Accounts',
    'login.invalid_credentials': 'Invalid credentials',
    'not_found.title': 'Page not found',
    'not_found.go_dashboard': 'Go to Dashboard',
    'org_chart.title': 'Organization Chart',
    'org_chart.employees': 'employees',
    'org_chart.no_employees': 'No employees',
    'org_chart.no_departments': 'No departments found',
    'status.approved': 'Approved',
    'status.pending': 'Pending',
    'status.rejected': 'Rejected',
    'status.paid': 'Paid',
    'status.present': 'Present',
    'status.late': 'Late',
    'status.absent': 'Absent',
    'status.active': 'Active',
    'status.draft': 'Draft',
    'status.half_day': 'Half Day',
    'status.applied': 'Applied',
    'status.screening': 'Screening',
    'status.interview': 'Interview',
    'status.offered': 'Offered',
    'status.hired': 'Hired',
    'validation.first_name_required': 'First name is required',
    'validation.last_name_required': 'Last name is required',
    'validation.position_required': 'Position is required',
    'validation.salary_positive': 'Salary must be positive',
    'validation.department_required': 'Department is required',
    'validation.hire_date_required': 'Hire date is required',
    'validation.user_id_required': 'User ID is required',
    'validation.new_value_required': 'New value is required',
    'validation.date_required': 'Date is required',
    'validation.start_date_required': 'Start date is required',
    'validation.end_date_required': 'End date is required',
    'validation.end_after_start': 'End date must be after start date',
    'employees.deleted': 'Employee deleted',
    'employees.delete_failed': 'Delete failed',
    'employees.bulk_deleted': 'employees deleted',
    'employees.selected': 'selected',
    'employees.delete_bulk': 'Delete',
    'employees.export_csv': 'Export CSV',
    'employees.total': 'total',
    'employees.previous': 'Previous',
    'employees.next': 'Next',
    'employees.create_record_sr': 'Create a new employee record',
    'employees.select': 'Select...',
    'employees.contract_type_label': 'Contract Type',
    'employees.none': 'None',
    'employees.contract_expiry_label': 'Contract Expiry',
    'employees.creating': 'Creating...',
    'employees.delete_title': 'Delete Employee',
    'employees.delete_confirm_sr': 'Confirm employee deletion',
    'employees.cancel': 'Cancel',
    'employees.deleting': 'Deleting...',
    'employees.delete': 'Delete',
    'employees.edit': 'Edit',
    'employees.updated': 'Employee updated',
    'employees.update_failed': 'Update failed',
    'employees.document_uploaded': 'Document uploaded',
    'employees.upload_failed': 'Upload failed',
    'employees.document_removed': 'Document removed',
    'employees.saving': 'Saving...',
    'employees.save': 'Save',
    'employees.upload_title': 'Upload Document',
    'employees.upload_sr': 'Upload a document for this employee',
    'employees.uploading': 'Uploading...',
    'employees.edit_title': 'Edit Employee',
    'employees.edit_sr': 'Edit employee details',
    'employees.no_documents': 'No documents uploaded',
    'departments.create_failed': 'Failed to create department',
    'departments.update_failed': 'Failed to update department',
    'departments.delete_failed': 'Failed to delete department',
    'departments.loading': 'Loading...',
    'departments.create_sr': 'Create a new department',
    'departments.edit_sr': 'Edit department details',
    'leaves.annual_leave': 'Annual Leave',
    'leaves.sick_leave': 'Sick Leave',
    'leaves.personal_leave': 'Personal Leave',
    'leaves.days': 'days',
    'leaves.submit_sr': 'Submit a leave request',
    'leaves.submitting': 'Submitting...',
    'leaves.approval_failed': 'Approval failed',
    'leaves.declined': 'Declined',
    'leaves.rejection_failed': 'Rejection failed',
    'leaves.loading': 'Loading...',
    'payroll.no_employees': 'No employees available',
    'performance_reviews.loading': 'Loading...',
    'performance_reviews.reviewed_by': 'Reviewed by',
    'performance_reviews.comments': 'Comments',
    'performance_reviews.goals': 'Goals',
    'performance_reviews.na': 'N/A',
    'performance_reviews.title': 'Performance Reviews',
    'performance_reviews.new_review': 'New Review',
    'performance_reviews.total_reviews': 'Total Reviews',
    'performance_reviews.avg_rating': 'Average Rating',
    'performance_reviews.submitted': 'Submitted',
    'performance_reviews.employee': 'Employee',
    'performance_reviews.period': 'Period',
    'performance_reviews.rating': 'Rating',
    'performance_reviews.status_heading': 'Status',
    'performance_reviews.actions_heading': 'Actions',
    'performance_reviews.no_reviews_found': 'No reviews found',
    'performance_reviews.new_title': 'New Performance Review',
    'performance_reviews.new_sr': 'Create a performance review',
    'performance_reviews.employee_label': 'Employee',
    'performance_reviews.select_employee': 'Select employee',
    'performance_reviews.period_label': 'Period (e.g. Q1 2026)',
    'performance_reviews.period_placeholder': 'Q1 2026',
    'performance_reviews.rating_label': 'Rating (1-5)',
    'performance_reviews.comments_label': 'Comments',
    'performance_reviews.goals_label': 'Goals',
    'performance_reviews.create_review': 'Create Review',
    'performance_reviews.edit_title': 'Edit Review',
    'performance_reviews.edit_sr': 'Update performance review',
    'performance_reviews.status_label': 'Status',
    'performance_reviews.draft_status': 'Draft',
    'performance_reviews.submitted_status': 'Submitted',
    'performance_reviews.acknowledged': 'Acknowledged',
    'performance_reviews.update_review': 'Update Review',
    'performance_reviews.created': 'Review created',
    'performance_reviews.updated': 'Review updated',
    'recruitment.job_postings': 'Job Postings',
    'recruitment.add_job': 'Add Job Posting',
    'recruitment.search_titles': 'Search job titles...',
    'recruitment.status': 'Status',
    'recruitment.all': 'All',
    'recruitment.open': 'Open',
    'recruitment.closed': 'Closed',
    'recruitment.draft': 'Draft',
    'recruitment.title': 'Title',
    'recruitment.department': 'Department',
    'recruitment.openings': 'Openings',
    'recruitment.actions': 'Actions',
    'recruitment.loading': 'Loading...',
    'recruitment.no_jobs': 'No job postings found',
    'recruitment.add_title': 'Add Job Posting',
    'recruitment.add_sr': 'Create a new job posting',
    'recruitment.title_label': 'Title',
    'recruitment.department_label': 'Department',
    'recruitment.select_department': 'Select department',
    'recruitment.description_label': 'Description',
    'recruitment.requirements_label': 'Requirements',
    'recruitment.status_label': 'Status',
    'recruitment.openings_label': 'Openings',
    'recruitment.create_job': 'Create Job Posting',
    'recruitment.edit_title': 'Edit Job Posting',
    'recruitment.edit_sr': 'Edit job posting details',
    'recruitment.update_job': 'Update Job Posting',
    'recruitment.delete_title': 'Delete Job Posting',
    'recruitment.delete_confirm': 'Are you sure you want to delete',
    'recruitment.delete_warning': 'This action cannot be undone.',
    'recruitment.cancel': 'Cancel',
    'recruitment.delete': 'Delete',
    'recruitment.job_created': 'Job posting created',
    'recruitment.job_updated': 'Job posting updated',
    'recruitment.job_deleted': 'Job posting deleted',
    'recruitment.candidates': 'Candidates',
    'recruitment.add_candidate': 'Add Candidate',
    'recruitment.search_candidates': 'Search candidates...',
    'recruitment.all_statuses': 'All Statuses',
    'recruitment.applied': 'Applied',
    'recruitment.screening': 'Screening',
    'recruitment.interview': 'Interview',
    'recruitment.offered': 'Offered',
    'recruitment.hired': 'Hired',
    'recruitment.rejected': 'Rejected',
    'recruitment.name': 'Name',
    'recruitment.email': 'Email',
    'recruitment.job_posting': 'Job Posting',
    'recruitment.applied_date': 'Applied',
    'recruitment.no_candidates': 'No candidates found',
    'recruitment.add_candidate_title': 'Add Candidate',
    'recruitment.add_candidate_sr': 'Create a new candidate record',
    'recruitment.first_name': 'First Name',
    'recruitment.last_name': 'Last Name',
    'recruitment.email_label': 'Email',
    'recruitment.phone_label': 'Phone',
    'recruitment.job_posting_label': 'Job Posting',
    'recruitment.select_job': 'Select job posting',
    'recruitment.notes_label': 'Notes',
    'recruitment.create_candidate': 'Create Candidate',
    'recruitment.edit_candidate_title': 'Edit Candidate',
    'recruitment.edit_candidate_sr': 'Update candidate details',
    'recruitment.update_candidate': 'Update Candidate',
    'recruitment.delete_candidate_title': 'Delete Candidate',
    'recruitment.delete_candidate_confirm': 'Are you sure you want to delete',
    'recruitment.candidate_created': 'Candidate created',
    'recruitment.candidate_updated': 'Candidate updated',
    'recruitment.candidate_deleted': 'Candidate deleted',
    'settings.sr': 'Application settings',
    'settings.english': 'English',
    'app.loading': 'Loading...',
    'auth.confirm_logout': 'Confirm Logout',
    'auth.confirm_logout_desc': 'Are you sure you want to log out?',
    'auth.confirm_pay': 'Confirm Payment',
    'auth.confirm_pay_desc': 'Mark this payroll record as paid? This action cannot be undone.',
    'auth.confirm_approve_leave': 'Confirm Approval',
    'auth.confirm_approve_leave_desc': 'Approve this leave request?',
    'auth.confirm_reject_leave': 'Confirm Rejection',
    'auth.confirm_reject_leave_desc': 'Reject this leave request?',
    'auth.confirm_bulk_delete': 'Confirm Bulk Delete',
    'auth.confirm_bulk_delete_desc': 'Delete {count} selected employees? This action cannot be undone.',
    'auth.confirm_remove_doc': 'Confirm Remove Document',
    'auth.confirm_remove_doc_desc': 'Remove this document? This action cannot be undone.',
  },
  vi: {
    'app.name': 'Quản lý Nhân sự',
    'role.admin': 'Quản trị viên',
    'role.manager': 'Quản lý',
    'role.employee': 'Nhân viên',
    'nav.dashboard': 'Tổng quan',
    'nav.employees': 'Nhân viên',
    'nav.departments': 'Phòng ban',
    'nav.org_chart': 'Sơ đồ tổ chức',
    'nav.leaves': 'Nghỉ phép',
    'nav.leave_approvals': 'Phê duyệt',
    'nav.attendance': 'Chấm công',
    'nav.attendance_report': 'Báo cáo',
    'nav.payroll': 'Lương',
    'nav.payroll_management': 'Quản lý lương',
    'nav.performance_reviews': 'Đánh giá',
    'nav.performance_management': 'Quản lý đánh giá',
    'nav.job_postings': 'Tin tuyển dụng',
    'nav.candidates': 'Ứng viên',
    'nav.notifications': 'Thông báo',
    'nav.logout': 'Đăng xuất',
    'performance_reviews.my_title': 'Đánh giá của tôi',
    'performance_reviews.description': 'Xem đánh giá hiệu suất của bạn',
    'performance_reviews.no_reviews': 'Không tìm thấy đánh giá nào',
    'settings': 'Cài đặt',
    'settings.language': 'Ngôn ngữ',
    'settings.theme': 'Giao diện',
    'settings.light': 'Sáng',
    'settings.dark': 'Tối',
    'user.edit_profile': 'Chỉnh sửa hồ sơ',
    'user.profile': 'Hồ sơ',
    'user.name': 'Tên',
    'user.email': 'Email',
    'user.role': 'Vai trò',
    'user.save': 'Lưu',
    'user.info': 'Thông tin người dùng',
    'dialog.cancel': 'Hủy',
    'profile.updated': 'Đã cập nhật hồ sơ',
    'profile.failed_update': 'Không thể cập nhật hồ sơ',
    'profile.security': 'Bảo mật',
    'profile.change_password': 'Đổi mật khẩu',
    'profile.edit_sr': 'Chỉnh sửa hồ sơ',
    'profile.password_sr': 'Cập nhật mật khẩu',
    'profile.current_password': 'Mật khẩu hiện tại',
    'profile.new_password': 'Mật khẩu mới',
    'profile.confirm_password': 'Xác nhận mật khẩu mới',
    'profile.passwords_mismatch': 'Mật khẩu không khớp',
    'profile.password_changed': 'Đổi mật khẩu thành công',
    'profile.password_failed': 'Không thể đổi mật khẩu',
    'dashboard.title': 'Tổng quan',
    'dashboard.total_employees': 'Tổng nhân viên',
    'dashboard.pending_leaves': 'Đơn chờ duyệt',
    'dashboard.present_today': 'Có mặt hôm nay',
    'dashboard.monthly_payroll': 'Lương tháng',
    'dashboard.recent_leaves': 'Đơn gần đây',
    'dashboard.quick_stats': 'Thống kê nhanh',
    'dashboard.no_leaves': 'Không có đơn nào',
    'dashboard.my_leaves': 'Đơn của tôi',
    'dashboard.my_attendance': 'Chấm công của tôi',
    'dashboard.welcome_back': 'Chào mừng trở lại',
    'dashboard.approved': 'Đã duyệt',
    'dashboard.rejected': 'Từ chối',
    'dashboard.present_month': 'Có mặt (Tháng này)',
    'dashboard.month_days': 'Ngày trong tháng',
    'dashboard.attendance_records': 'bản ghi chấm công',
    'dashboard.leave_breakdown': 'Phân tích nghỉ phép',
    'dashboard.no_leave_data': 'Không có dữ liệu nghỉ phép',
    'dashboard.attendance_month': 'Chấm công (Tháng này)',
    'dashboard.no_attendance_data': 'Không có dữ liệu chấm công',
    'dashboard.upcoming_leaves': 'Sắp nghỉ phép',
    'dashboard.present': 'Có mặt',
    'dashboard.late': 'Đi muộn',
    'dashboard.half_day': 'Nửa ngày',
    'dashboard.absent': 'Vắng',
    'dashboard.team_overview': 'Tổng quan nhóm',
    'dashboard.company_overview': 'Tổng quan công ty',
    'dashboard.employees_per_dept': 'Nhân viên theo phòng',
    'dashboard.no_department_data': 'Không có dữ liệu phòng ban',
    'dashboard.department_title': 'Phòng ban',
    'dashboard.team_size': 'Quy mô nhóm',
    'dashboard.dept_payroll': 'Lương phòng',
    'dashboard.na': 'N/A',
    'dashboard.pending': 'đang chờ',
    'dashboard.days': 'ngày',
    'dashboard.employees': 'Nhân viên',
    'dashboard.departments': 'Phòng ban',
    'employees.title': 'Nhân viên',
    'employees.add': 'Thêm nhân viên',
    'employees.search': 'Tìm nhân viên...',
    'employees.name': 'Họ tên',
    'employees.position': 'Chức vụ',
    'employees.department': 'Phòng ban',
    'employees.salary': 'Lương',
    'employees.no_results': 'Không tìm thấy nhân viên',
    'employees.first_name': 'Tên',
    'employees.last_name': 'Họ',
    'employees.hire_date': 'Ngày vào làm',
    'employees.phone': 'Số điện thoại',
    'employees.user_id': 'Mã người dùng',
    'employees.user_id_placeholder': 'Mã người dùng từ đăng ký',
    'employees.create': 'Tạo',
    'departments.title': 'Phòng ban',
    'departments.add': 'Thêm phòng ban',
    'departments.search': 'Tìm phòng ban...',
    'departments.name': 'Tên',
    'departments.description': 'Mô tả',
    'departments.manager': 'Quản lý',
    'departments.actions': 'Thao tác',
    'departments.no_results': 'Không có phòng ban',
    'departments.create': 'Tạo',
    'departments.edit': 'Sửa phòng ban',
    'departments.save': 'Lưu',
    'departments.delete': 'Xóa phòng ban',
    'departments.delete_confirm': 'Bạn có chắc muốn xóa',
    'departments.delete_warning': 'Hành động này không thể hoàn tác.',
    'departments.created': 'Đã tạo phòng ban',
    'departments.updated': 'Đã cập nhật phòng ban',
    'departments.deleted': 'Đã xóa phòng ban',
    'leaves.title': 'Đơn nghỉ phép',
    'leaves.request': 'Tạo đơn',
    'leaves.type': 'Loại',
    'leaves.start': 'Bắt đầu',
    'leaves.end': 'Kết thúc',
    'leaves.status': 'Trạng thái',
    'leaves.reason': 'Lý do',
    'leaves.no_results': 'Không có đơn nào',
    'leaves.request_title': 'Tạo đơn nghỉ phép',
    'leaves.annual': 'Năm',
    'leaves.sick': 'Ốm',
    'leaves.personal': 'Cá nhân',
    'leaves.start_date': 'Ngày bắt đầu',
    'leaves.end_date': 'Ngày kết thúc',
    'leaves.submit': 'Gửi',
    'leaves.approvals': 'Phê duyệt đơn',
    'leaves.employee': 'Nhân viên',
    'leaves.actions': 'Thao tác',
    'leaves.no_pending': 'Không có đơn chờ duyệt',
    'attendance.title': 'Chấm công',
    'attendance.check_in': 'Vào',
    'attendance.check_out': 'Ra',
    'attendance.date': 'Ngày',
    'attendance.status': 'Trạng thái',
    'attendance.no_records': 'Không có dữ liệu',
    'attendance.already_checked_in': 'Đã chấm công hôm nay',
    'attendance.check_out_failed': 'Không thể chấm công ra',
    'attendance.report': 'Báo cáo chấm công',
    'attendance.employee': 'Nhân viên',
    'payroll.title': 'Bảng lương',
    'payroll.period': 'Kỳ',
    'payroll.basic_salary': 'Lương cơ bản',
    'payroll.bonus': 'Thưởng',
    'payroll.deductions': 'Khấu trừ',
    'payroll.net_pay': 'Thực nhận',
    'payroll.status': 'Trạng thái',
    'payroll.no_records': 'Không có dữ liệu lương',
    'payroll.management': 'Quản lý lương',
    'payroll.process': 'Xử lý lương',
    'payroll.employee': 'Nhân viên',
    'payroll.actions': 'Thao tác',
    'payroll.mark_paid': 'Đã trả',
    'payroll.month': 'Tháng',
    'payroll.year': 'Năm',
    'payroll.employees': 'Nhân viên',
    'payroll.process_btn': 'Xử lý',
    'payroll.no_records_management': 'Không có dữ liệu lương',
    'payroll.total_paid': 'Tổng đã trả',
    'payroll.waiting': 'Chờ xử lý',
    'payroll.paid': 'Đã trả',
    'payroll.draft': 'Nháp',
    'payroll.gross': 'Tổng lương',
    'payroll.process_description': 'Xử lý bảng lương cho nhân viên đã chọn',
    'employees.contract': 'Hợp đồng',
    'employees.contract_type': 'Loại hợp đồng',
    'employees.contract_expiry': 'Ngày hết hạn',
    'employees.contract_permanent': 'Chính thức',
    'employees.contract_contract': 'Hợp đồng',
    'employees.contract_intern': 'Thực tập',
    'employees.documents': 'Tài liệu',
    'employees.history': 'Lịch sử nhân viên',
    'employees.history_add': 'Thêm mới',
    'employees.history_title': 'Thêm lịch sử',
    'employees.history_type': 'Loại',
    'employees.history_previous': 'Giá trị cũ',
    'employees.history_new': 'Giá trị mới',
    'employees.history_date': 'Ngày hiệu lực',
    'employees.history_note': 'Ghi chú',
    'employees.history_save': 'Lưu',
    'employees.history_added': 'Đã thêm lịch sử',
    'employees.not_found': 'Không tìm thấy nhân viên',
    'employees.no_history': 'Chưa có lịch sử',
    'employees.history_previous_placeholder': 'VD: 5.000.000đ / Nhân viên',
    'employees.history_new_placeholder': 'VD: 7.000.000đ / Trưởng nhóm',
    'employees.history_note_placeholder': 'Ghi chú (không bắt buộc)',
    'history.raise': 'Tăng lương',
    'history.promotion': 'Thăng chức',
    'history.transfer': 'Chuyển phòng',
    'history.other': 'Khác',
    'common.loading': 'Đang tải...',
    'common.search': 'Tìm kiếm',
    'notifications.unread': 'chưa đọc',
    'notifications.all_caught_up': 'Đã xem hết',
    'notifications.mark_all_read': 'Đánh dấu đã đọc',
    'notifications.no_notifications': 'Không có thông báo',
    'notifications.up_to_date': 'Bạn đã xem hết thông báo',
    'notifications.failed_mark_read': 'Không thể đánh dấu đã đọc',
    'login.sign_in_to_account': 'Đăng nhập vào tài khoản',
    'login.email': 'Email',
    'login.password': 'Mật khẩu',
    'login.sign_in': 'Đăng nhập',
    'login.demo_accounts': 'Tài khoản dùng thử',
    'login.invalid_credentials': 'Thông tin đăng nhập không hợp lệ',
    'not_found.title': 'Không tìm thấy trang',
    'not_found.go_dashboard': 'Về trang chủ',
    'org_chart.title': 'Sơ đồ tổ chức',
    'org_chart.employees': 'nhân viên',
    'org_chart.no_employees': 'Không có nhân viên',
    'org_chart.no_departments': 'Không tìm thấy phòng ban',
    'status.approved': 'Đã duyệt',
    'status.pending': 'Chờ duyệt',
    'status.rejected': 'Từ chối',
    'status.paid': 'Đã trả',
    'status.present': 'Có mặt',
    'status.late': 'Đi muộn',
    'status.absent': 'Vắng',
    'status.active': 'Đang làm',
    'status.draft': 'Bản nháp',
    'status.half_day': 'Nửa ngày',
    'status.applied': 'Đã ứng tuyển',
    'status.screening': 'Đang xét',
    'status.interview': 'Phỏng vấn',
    'status.offered': 'Đã đề nghị',
    'status.hired': 'Đã tuyển',
    'validation.first_name_required': 'Tên là bắt buộc',
    'validation.last_name_required': 'Họ là bắt buộc',
    'validation.position_required': 'Chức vụ là bắt buộc',
    'validation.salary_positive': 'Lương phải là số dương',
    'validation.department_required': 'Phòng ban là bắt buộc',
    'validation.hire_date_required': 'Ngày vào làm là bắt buộc',
    'validation.user_id_required': 'Mã người dùng là bắt buộc',
    'validation.new_value_required': 'Giá trị mới là bắt buộc',
    'validation.date_required': 'Ngày là bắt buộc',
    'validation.start_date_required': 'Ngày bắt đầu là bắt buộc',
    'validation.end_date_required': 'Ngày kết thúc là bắt buộc',
    'validation.end_after_start': 'Ngày kết thúc phải sau ngày bắt đầu',
    'employees.deleted': 'Đã xóa nhân viên',
    'employees.delete_failed': 'Xóa thất bại',
    'employees.bulk_deleted': 'nhân viên đã xóa',
    'employees.selected': 'đã chọn',
    'employees.delete_bulk': 'Xóa',
    'employees.export_csv': 'Xuất CSV',
    'employees.total': 'tổng',
    'employees.previous': 'Trước',
    'employees.next': 'Sau',
    'employees.create_record_sr': 'Tạo hồ sơ nhân viên mới',
    'employees.select': 'Chọn...',
    'employees.contract_type_label': 'Loại hợp đồng',
    'employees.none': 'Không',
    'employees.contract_expiry_label': 'Ngày hết hạn hợp đồng',
    'employees.creating': 'Đang tạo...',
    'employees.delete_title': 'Xóa nhân viên',
    'employees.delete_confirm_sr': 'Xác nhận xóa nhân viên',
    'employees.cancel': 'Hủy',
    'employees.deleting': 'Đang xóa...',
    'employees.delete': 'Xóa',
    'employees.edit': 'Chỉnh sửa',
    'employees.updated': 'Đã cập nhật nhân viên',
    'employees.update_failed': 'Cập nhật thất bại',
    'employees.document_uploaded': 'Đã tải tài liệu lên',
    'employees.upload_failed': 'Tải lên thất bại',
    'employees.document_removed': 'Đã xóa tài liệu',
    'employees.saving': 'Đang lưu...',
    'employees.save': 'Lưu',
    'employees.upload_title': 'Tải tài liệu lên',
    'employees.upload_sr': 'Tải tài liệu cho nhân viên này',
    'employees.uploading': 'Đang tải lên...',
    'employees.edit_title': 'Sửa nhân viên',
    'employees.edit_sr': 'Chỉnh sửa thông tin nhân viên',
    'employees.no_documents': 'Chưa có tài liệu nào',
    'departments.create_failed': 'Không thể tạo phòng ban',
    'departments.update_failed': 'Không thể cập nhật phòng ban',
    'departments.delete_failed': 'Không thể xóa phòng ban',
    'departments.loading': 'Đang tải...',
    'departments.create_sr': 'Tạo phòng ban mới',
    'departments.edit_sr': 'Chỉnh sửa thông tin phòng ban',
    'leaves.annual_leave': 'Nghỉ năm',
    'leaves.sick_leave': 'Nghỉ ốm',
    'leaves.personal_leave': 'Nghỉ cá nhân',
    'leaves.days': 'ngày',
    'leaves.submit_sr': 'Gửi đơn nghỉ phép',
    'leaves.submitting': 'Đang gửi...',
    'leaves.approval_failed': 'Duyệt đơn thất bại',
    'leaves.declined': 'Đã từ chối',
    'leaves.rejection_failed': 'Từ chối thất bại',
    'leaves.loading': 'Đang tải...',
    'payroll.no_employees': 'Không có nhân viên',
    'performance_reviews.loading': 'Đang tải...',
    'performance_reviews.reviewed_by': 'Đánh giá bởi',
    'performance_reviews.comments': 'Nhận xét',
    'performance_reviews.goals': 'Mục tiêu',
    'performance_reviews.na': 'N/A',
    'performance_reviews.title': 'Đánh giá hiệu suất',
    'performance_reviews.new_review': 'Đánh giá mới',
    'performance_reviews.total_reviews': 'Tổng đánh giá',
    'performance_reviews.avg_rating': 'Điểm trung bình',
    'performance_reviews.submitted': 'Đã gửi',
    'performance_reviews.employee': 'Nhân viên',
    'performance_reviews.period': 'Kỳ',
    'performance_reviews.rating': 'Điểm',
    'performance_reviews.status_heading': 'Trạng thái',
    'performance_reviews.actions_heading': 'Thao tác',
    'performance_reviews.no_reviews_found': 'Không tìm thấy đánh giá',
    'performance_reviews.new_title': 'Đánh giá hiệu suất mới',
    'performance_reviews.new_sr': 'Tạo đánh giá hiệu suất',
    'performance_reviews.employee_label': 'Nhân viên',
    'performance_reviews.select_employee': 'Chọn nhân viên',
    'performance_reviews.period_label': 'Kỳ (VD: Q1 2026)',
    'performance_reviews.period_placeholder': 'Q1 2026',
    'performance_reviews.rating_label': 'Điểm (1-5)',
    'performance_reviews.comments_label': 'Nhận xét',
    'performance_reviews.goals_label': 'Mục tiêu',
    'performance_reviews.create_review': 'Tạo đánh giá',
    'performance_reviews.edit_title': 'Sửa đánh giá',
    'performance_reviews.edit_sr': 'Cập nhật đánh giá hiệu suất',
    'performance_reviews.status_label': 'Trạng thái',
    'performance_reviews.draft_status': 'Nháp',
    'performance_reviews.submitted_status': 'Đã gửi',
    'performance_reviews.acknowledged': 'Đã xác nhận',
    'performance_reviews.update_review': 'Cập nhật đánh giá',
    'performance_reviews.created': 'Đã tạo đánh giá',
    'performance_reviews.updated': 'Đã cập nhật đánh giá',
    'recruitment.job_postings': 'Tin tuyển dụng',
    'recruitment.add_job': 'Thêm tin tuyển dụng',
    'recruitment.search_titles': 'Tìm tiêu đề...',
    'recruitment.status': 'Trạng thái',
    'recruitment.all': 'Tất cả',
    'recruitment.open': 'Đang tuyển',
    'recruitment.closed': 'Đã đóng',
    'recruitment.draft': 'Nháp',
    'recruitment.title': 'Tiêu đề',
    'recruitment.department': 'Phòng ban',
    'recruitment.openings': 'Số lượng',
    'recruitment.actions': 'Thao tác',
    'recruitment.loading': 'Đang tải...',
    'recruitment.no_jobs': 'Không tìm thấy tin tuyển dụng',
    'recruitment.add_title': 'Thêm tin tuyển dụng',
    'recruitment.add_sr': 'Tạo tin tuyển dụng mới',
    'recruitment.title_label': 'Tiêu đề',
    'recruitment.department_label': 'Phòng ban',
    'recruitment.select_department': 'Chọn phòng ban',
    'recruitment.description_label': 'Mô tả',
    'recruitment.requirements_label': 'Yêu cầu',
    'recruitment.status_label': 'Trạng thái',
    'recruitment.openings_label': 'Số lượng',
    'recruitment.create_job': 'Tạo tin tuyển dụng',
    'recruitment.edit_title': 'Sửa tin tuyển dụng',
    'recruitment.edit_sr': 'Chỉnh sửa tin tuyển dụng',
    'recruitment.update_job': 'Cập nhật tin tuyển dụng',
    'recruitment.delete_title': 'Xóa tin tuyển dụng',
    'recruitment.delete_confirm': 'Bạn có chắc muốn xóa',
    'recruitment.delete_warning': 'Hành động này không thể hoàn tác.',
    'recruitment.cancel': 'Hủy',
    'recruitment.delete': 'Xóa',
    'recruitment.job_created': 'Đã tạo tin tuyển dụng',
    'recruitment.job_updated': 'Đã cập nhật tin tuyển dụng',
    'recruitment.job_deleted': 'Đã xóa tin tuyển dụng',
    'recruitment.candidates': 'Ứng viên',
    'recruitment.add_candidate': 'Thêm ứng viên',
    'recruitment.search_candidates': 'Tìm ứng viên...',
    'recruitment.all_statuses': 'Tất cả trạng thái',
    'recruitment.applied': 'Đã nộp',
    'recruitment.screening': 'Đang xét',
    'recruitment.interview': 'Phỏng vấn',
    'recruitment.offered': 'Đã đề nghị',
    'recruitment.hired': 'Đã tuyển',
    'recruitment.rejected': 'Từ chối',
    'recruitment.name': 'Họ tên',
    'recruitment.email': 'Email',
    'recruitment.job_posting': 'Tin tuyển dụng',
    'recruitment.applied_date': 'Ngày nộp',
    'recruitment.no_candidates': 'Không tìm thấy ứng viên',
    'recruitment.add_candidate_title': 'Thêm ứng viên',
    'recruitment.add_candidate_sr': 'Tạo hồ sơ ứng viên mới',
    'recruitment.first_name': 'Tên',
    'recruitment.last_name': 'Họ',
    'recruitment.email_label': 'Email',
    'recruitment.phone_label': 'Số điện thoại',
    'recruitment.job_posting_label': 'Tin tuyển dụng',
    'recruitment.select_job': 'Chọn tin tuyển dụng',
    'recruitment.notes_label': 'Ghi chú',
    'recruitment.create_candidate': 'Tạo ứng viên',
    'recruitment.edit_candidate_title': 'Sửa ứng viên',
    'recruitment.edit_candidate_sr': 'Cập nhật thông tin ứng viên',
    'recruitment.update_candidate': 'Cập nhật ứng viên',
    'recruitment.delete_candidate_title': 'Xóa ứng viên',
    'recruitment.delete_candidate_confirm': 'Bạn có chắc muốn xóa',
    'recruitment.candidate_created': 'Đã tạo ứng viên',
    'recruitment.candidate_updated': 'Đã cập nhật ứng viên',
    'recruitment.candidate_deleted': 'Đã xóa ứng viên',
    'settings.sr': 'Cài đặt ứng dụng',
    'settings.english': 'English',
    'app.loading': 'Đang tải...',
    'auth.confirm_logout': 'Xác nhận đăng xuất',
    'auth.confirm_logout_desc': 'Bạn có chắc muốn đăng xuất?',
    'auth.confirm_pay': 'Xác nhận thanh toán',
    'auth.confirm_pay_desc': 'Đánh dấu bảng lương này đã thanh toán? Hành động này không thể hoàn tác.',
    'auth.confirm_approve_leave': 'Xác nhận duyệt đơn',
    'auth.confirm_approve_leave_desc': 'Duyệt đơn nghỉ phép này?',
    'auth.confirm_reject_leave': 'Xác nhận từ chối',
    'auth.confirm_reject_leave_desc': 'Từ chối đơn nghỉ phép này?',
    'auth.confirm_bulk_delete': 'Xác nhận xóa hàng loạt',
    'auth.confirm_bulk_delete_desc': 'Xóa {count} nhân viên đã chọn? Hành động này không thể hoàn tác.',
    'auth.confirm_remove_doc': 'Xác nhận xóa tài liệu',
    'auth.confirm_remove_doc_desc': 'Xóa tài liệu này? Hành động này không thể hoàn tác.',
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem('lang') as Lang) || 'en');

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('lang', l);
  };

  const t = useCallback((key: string) => translations[lang][key] || key, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  return useContext(LanguageContext);
}
