import { createContext, useContext, useState, ReactNode, useCallback } from 'react';

export type Lang = 'en' | 'vi';

const translations: Record<Lang, Record<string, string>> = {
  en: {
    'app.name': 'HR Management',
    'nav.dashboard': 'Dashboard',
    'nav.employees': 'Employees',
    'nav.departments': 'Departments',
    'nav.org_chart': 'Org Chart',
    'nav.leaves': 'Leaves',
    'nav.leave_approvals': 'Leave Approvals',
    'nav.attendance': 'Attendance',
    'nav.attendance_report': 'Attendance Report',
    'nav.payroll': 'Payroll',
    'nav.payroll_mgmt': 'Payroll Mgmt',
    'nav.logout': 'Logout',
    'settings': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'user.edit_profile': 'Edit Profile',
    'user.profile': 'Profile',
    'user.name': 'Name',
    'user.email': 'Email',
    'user.role': 'Role',
    'user.save': 'Save',
    'user.info': 'User Information',
    'dialog.cancel': 'Cancel',
    'profile.updated': 'Profile updated',
    'dashboard.title': 'Dashboard',
    'dashboard.total_employees': 'Total Employees',
    'dashboard.pending_leaves': 'Pending Leaves',
    'dashboard.present_today': 'Present Today',
    'dashboard.monthly_payroll': 'Monthly Payroll',
    'dashboard.recent_leaves': 'Recent Leaves',
    'dashboard.quick_stats': 'Quick Stats',
    'dashboard.no_leaves': 'No leaves found',
    'dashboard.my_leaves': 'My Leaves',
    'dashboard.my_attendance': 'My Attendance',
    'dashboard.pending': 'pending',
    'dashboard.days': 'days',
    'dashboard.employees': 'Employees',
    'dashboard.departments': 'Departments',
    'employees.title': 'Employees',
    'employees.add': 'Add Employee',
    'employees.search': 'Search employees...',
    'employees.name': 'Name',
    'employees.position': 'Position',
    'employees.department': 'Department',
    'employees.salary': 'Salary',
    'employees.no_results': 'No employees found',
    'employees.first_name': 'First Name',
    'employees.last_name': 'Last Name',
    'employees.hire_date': 'Hire Date',
    'employees.phone': 'Phone',
    'employees.user_id': 'User ID',
    'employees.user_id_placeholder': 'User ID from registration',
    'employees.create': 'Create',
    'departments.title': 'Departments',
    'departments.add': 'Add Department',
    'departments.search': 'Search departments...',
    'departments.name': 'Name',
    'departments.description': 'Description',
    'departments.manager': 'Manager',
    'departments.actions': 'Actions',
    'departments.no_results': 'No departments',
    'departments.create': 'Create',
    'departments.edit': 'Edit Department',
    'departments.save': 'Save',
    'departments.delete': 'Delete Department',
    'departments.delete_confirm': 'Are you sure you want to delete',
    'departments.delete_warning': 'This action cannot be undone.',
    'departments.created': 'Department created',
    'departments.updated': 'Department updated',
    'departments.deleted': 'Department deleted',
    'leaves.title': 'My Leaves',
    'leaves.request': 'Request Leave',
    'leaves.type': 'Type',
    'leaves.start': 'Start',
    'leaves.end': 'End',
    'leaves.status': 'Status',
    'leaves.reason': 'Reason',
    'leaves.no_results': 'No leaves',
    'leaves.request_title': 'Request Leave',
    'leaves.annual': 'Annual',
    'leaves.sick': 'Sick',
    'leaves.personal': 'Personal',
    'leaves.start_date': 'Start Date',
    'leaves.end_date': 'End Date',
    'leaves.submit': 'Submit',
    'leaves.approvals': 'Leave Approvals',
    'leaves.employee': 'Employee',
    'leaves.actions': 'Actions',
    'leaves.no_pending': 'No pending leaves',
    'attendance.title': 'My Attendance',
    'attendance.check_in': 'Check In',
    'attendance.check_out': 'Check Out',
    'attendance.date': 'Date',
    'attendance.status': 'Status',
    'attendance.no_records': 'No records',
    'attendance.report': 'Attendance Report',
    'attendance.employee': 'Employee',
    'payroll.title': 'My Payroll',
    'payroll.period': 'Period',
    'payroll.basic_salary': 'Basic Salary',
    'payroll.bonus': 'Bonus',
    'payroll.deductions': 'Deductions',
    'payroll.net_pay': 'Net Pay',
    'payroll.status': 'Status',
    'payroll.no_records': 'No payroll records',
    'payroll.management': 'Payroll Management',
    'payroll.process': 'Process Payroll',
    'payroll.employee': 'Employee',
    'payroll.actions': 'Actions',
    'payroll.mark_paid': 'Mark Paid',
    'payroll.month': 'Month',
    'payroll.year': 'Year',
    'payroll.employees': 'Employees',
    'payroll.process_btn': 'Process',
    'payroll.no_records_mgmt': 'No payroll records',
    'payroll.total_paid': 'Total Paid',
    'payroll.waiting': 'Waiting',
    'payroll.paid': 'Paid',
    'payroll.draft': 'Draft',
    'payroll.gross': 'Gross Pay',
    'payroll.process_description': 'Process payroll for selected employees',
    'employees.contract': 'Contract',
    'employees.contract_type': 'Contract Type',
    'employees.contract_expiry': 'Contract Expiry',
    'employees.contract_permanent': 'Permanent',
    'employees.contract_contract': 'Contract',
    'employees.contract_intern': 'Intern',
    'employees.documents': 'Documents',
    'employees.history': 'Employee History',
    'employees.history_add': 'Add Entry',
    'employees.history_title': 'Add History Entry',
    'employees.history_type': 'Type',
    'employees.history_previous': 'Previous Value',
    'employees.history_new': 'New Value',
    'employees.history_date': 'Effective Date',
    'employees.history_note': 'Note',
    'employees.history_save': 'Save',
    'employees.history_added': 'History entry added',
    'employees.not_found': 'Employee not found',
    'employees.no_history': 'No history entries',
    'employees.history_previous_placeholder': 'e.g. $3,000 / Junior',
    'employees.history_new_placeholder': 'e.g. $4,000 / Senior',
    'employees.history_note_placeholder': 'Optional note',
    'history.raise': 'Raise',
    'history.promotion': 'Promotion',
    'history.transfer': 'Transfer',
    'history.other': 'Other',
    'common.loading': 'Loading...',
    'common.search': 'Search',
  },
  vi: {
    'app.name': 'Quản lý Nhân sự',
    'nav.dashboard': 'Tổng quan',
    'nav.employees': 'Nhân viên',
    'nav.departments': 'Phòng ban',
    'nav.org_chart': 'Sơ đồ tổ chức',
    'nav.leaves': 'Nghỉ phép',
    'nav.leave_approvals': 'Phê duyệt',
    'nav.attendance': 'Chấm công',
    'nav.attendance_report': 'Báo cáo',
    'nav.payroll': 'Lương',
    'nav.payroll_mgmt': 'Quản lý lương',
    'nav.logout': 'Đăng xuất',
    'settings': 'Cài đặt',
    'settings.language': 'Ngôn ngữ',
    'settings.theme': 'Giao diện',
    'settings.light': 'Sáng',
    'settings.dark': 'Tối',
    'user.edit_profile': 'Chỉnh sửa hồ sơ',
    'user.profile': 'Hồ sơ',
    'user.name': 'Tên',
    'user.email': 'Email',
    'user.role': 'Vai trò',
    'user.save': 'Lưu',
    'user.info': 'Thông tin người dùng',
    'dialog.cancel': 'Hủy',
    'profile.updated': 'Đã cập nhật hồ sơ',
    'dashboard.title': 'Tổng quan',
    'dashboard.total_employees': 'Tổng nhân viên',
    'dashboard.pending_leaves': 'Đơn chờ duyệt',
    'dashboard.present_today': 'Có mặt hôm nay',
    'dashboard.monthly_payroll': 'Lương tháng',
    'dashboard.recent_leaves': 'Đơn gần đây',
    'dashboard.quick_stats': 'Thống kê nhanh',
    'dashboard.no_leaves': 'Không có đơn nào',
    'dashboard.my_leaves': 'Đơn của tôi',
    'dashboard.my_attendance': 'Chấm công của tôi',
    'dashboard.pending': 'đang chờ',
    'dashboard.days': 'ngày',
    'dashboard.employees': 'Nhân viên',
    'dashboard.departments': 'Phòng ban',
    'employees.title': 'Nhân viên',
    'employees.add': 'Thêm nhân viên',
    'employees.search': 'Tìm nhân viên...',
    'employees.name': 'Họ tên',
    'employees.position': 'Chức vụ',
    'employees.department': 'Phòng ban',
    'employees.salary': 'Lương',
    'employees.no_results': 'Không tìm thấy nhân viên',
    'employees.first_name': 'Tên',
    'employees.last_name': 'Họ',
    'employees.hire_date': 'Ngày vào làm',
    'employees.phone': 'Số điện thoại',
    'employees.user_id': 'Mã người dùng',
    'employees.user_id_placeholder': 'Mã người dùng từ đăng ký',
    'employees.create': 'Tạo',
    'departments.title': 'Phòng ban',
    'departments.add': 'Thêm phòng ban',
    'departments.search': 'Tìm phòng ban...',
    'departments.name': 'Tên',
    'departments.description': 'Mô tả',
    'departments.manager': 'Quản lý',
    'departments.actions': 'Thao tác',
    'departments.no_results': 'Không có phòng ban',
    'departments.create': 'Tạo',
    'departments.edit': 'Sửa phòng ban',
    'departments.save': 'Lưu',
    'departments.delete': 'Xóa phòng ban',
    'departments.delete_confirm': 'Bạn có chắc muốn xóa',
    'departments.delete_warning': 'Hành động này không thể hoàn tác.',
    'departments.created': 'Đã tạo phòng ban',
    'departments.updated': 'Đã cập nhật phòng ban',
    'departments.deleted': 'Đã xóa phòng ban',
    'leaves.title': 'Đơn nghỉ phép',
    'leaves.request': 'Tạo đơn',
    'leaves.type': 'Loại',
    'leaves.start': 'Bắt đầu',
    'leaves.end': 'Kết thúc',
    'leaves.status': 'Trạng thái',
    'leaves.reason': 'Lý do',
    'leaves.no_results': 'Không có đơn nào',
    'leaves.request_title': 'Tạo đơn nghỉ phép',
    'leaves.annual': 'Năm',
    'leaves.sick': 'Ốm',
    'leaves.personal': 'Cá nhân',
    'leaves.start_date': 'Ngày bắt đầu',
    'leaves.end_date': 'Ngày kết thúc',
    'leaves.submit': 'Gửi',
    'leaves.approvals': 'Phê duyệt đơn',
    'leaves.employee': 'Nhân viên',
    'leaves.actions': 'Thao tác',
    'leaves.no_pending': 'Không có đơn chờ duyệt',
    'attendance.title': 'Chấm công',
    'attendance.check_in': 'Check In',
    'attendance.check_out': 'Check Out',
    'attendance.date': 'Ngày',
    'attendance.status': 'Trạng thái',
    'attendance.no_records': 'Không có dữ liệu',
    'attendance.report': 'Báo cáo chấm công',
    'attendance.employee': 'Nhân viên',
    'payroll.title': 'Bảng lương',
    'payroll.period': 'Kỳ',
    'payroll.basic_salary': 'Lương cơ bản',
    'payroll.bonus': 'Thưởng',
    'payroll.deductions': 'Khấu trừ',
    'payroll.net_pay': 'Thực nhận',
    'payroll.status': 'Trạng thái',
    'payroll.no_records': 'Không có dữ liệu lương',
    'payroll.management': 'Quản lý lương',
    'payroll.process': 'Xử lý lương',
    'payroll.employee': 'Nhân viên',
    'payroll.actions': 'Thao tác',
    'payroll.mark_paid': 'Đã trả',
    'payroll.month': 'Tháng',
    'payroll.year': 'Năm',
    'payroll.employees': 'Nhân viên',
    'payroll.process_btn': 'Xử lý',
    'payroll.no_records_mgmt': 'Không có dữ liệu lương',
    'payroll.total_paid': 'Tổng đã trả',
    'payroll.waiting': 'Chờ xử lý',
    'payroll.paid': 'Đã trả',
    'payroll.draft': 'Nháp',
    'payroll.gross': 'Tổng lương',
    'payroll.process_description': 'Xử lý bảng lương cho nhân viên đã chọn',
    'employees.contract': 'Hợp đồng',
    'employees.contract_type': 'Loại hợp đồng',
    'employees.contract_expiry': 'Ngày hết hạn',
    'employees.contract_permanent': 'Chính thức',
    'employees.contract_contract': 'Hợp đồng',
    'employees.contract_intern': 'Thực tập',
    'employees.documents': 'Tài liệu',
    'employees.history': 'Lịch sử nhân viên',
    'employees.history_add': 'Thêm mới',
    'employees.history_title': 'Thêm lịch sử',
    'employees.history_type': 'Loại',
    'employees.history_previous': 'Giá trị cũ',
    'employees.history_new': 'Giá trị mới',
    'employees.history_date': 'Ngày hiệu lực',
    'employees.history_note': 'Ghi chú',
    'employees.history_save': 'Lưu',
    'employees.history_added': 'Đã thêm lịch sử',
    'employees.not_found': 'Không tìm thấy nhân viên',
    'employees.no_history': 'Chưa có lịch sử',
    'employees.history_previous_placeholder': 'VD: 5.000.000đ / Nhân viên',
    'employees.history_new_placeholder': 'VD: 7.000.000đ / Trưởng nhóm',
    'employees.history_note_placeholder': 'Ghi chú (không bắt buộc)',
    'history.raise': 'Tăng lương',
    'history.promotion': 'Thăng chức',
    'history.transfer': 'Chuyển phòng',
    'history.other': 'Khác',
    'common.loading': 'Đang tải...',
    'common.search': 'Tìm kiếm',
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({} as LanguageContextType);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => (localStorage.getItem('lang') as Lang) || 'en');

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('lang', l);
  };

  const t = useCallback((key: string) => translations[lang][key] || key, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useTranslation() {
  return useContext(LanguageContext);
}
